version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        FOR_DEVELOPMENT: 'true'
    command: bash -c "python msg_split.py --max-len=4096 --source=./source.html"
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend

networks:
  default:
    name: network