version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        FOR_DEVELOPMENT: 'true'
    command: bash -c "poetry run flake8 && poetry run pytest"
    env_file:
      - .env
